version: '3'

services:
    web:
        container_name: revisionalpha
        build: .
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            - APACHE_SERVER_NAME=revisionalpha.local
        networks:
            - webnet
networks:
    webnet:
